local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  transform_rolerance: 2.4
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  # plugins:
  #   - {name: static_layer, type: "costmap_2d::StaticLayer"}      
  #   # - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #   # - {name: depth_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
